name: Docker Image CI

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: taoky/M.A.R.S

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      run: docker push ${{ steps.meta.outputs.tags }}
